/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.Order;

/**
 *
 * @author Faruk
 */
public class OrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPanel
     */
    public OrdersPanel() {
        initComponents();
//        ordersTable.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addOrdersNvg = new javax.swing.JButton();
        changeOrdersNvg = new javax.swing.JButton();
        deleteOrdersNvg = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        totalOrdersLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        printOrdersNvg = new javax.swing.JButton();

        addOrdersNvg.setText("Tambah");
        addOrdersNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrdersNvgActionPerformed(evt);
            }
        });

        changeOrdersNvg.setText("Ubah");
        changeOrdersNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeOrdersNvgActionPerformed(evt);
            }
        });

        deleteOrdersNvg.setText("Hapus");
        deleteOrdersNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteOrdersNvgActionPerformed(evt);
            }
        });

        jLabel19.setText("Info");

        jLabel20.setText("Lainnya");

        jLabel21.setText("TOTAL PESANAN");

        totalOrdersLabel.setText("0");

        jLabel1.setText("Daftar Pesanan Pupuk");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(ordersTable);

        printOrdersNvg.setText("Print");
        printOrdersNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printOrdersNvgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printOrdersNvg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteOrdersNvg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeOrdersNvg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addOrdersNvg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(86, 86, 86)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(totalOrdersLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrdersNvg)
                    .addComponent(changeOrdersNvg)
                    .addComponent(deleteOrdersNvg)
                    .addComponent(printOrdersNvg))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(totalOrdersLabel)))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrdersNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrdersNvgActionPerformed
        CardLayout cl = (CardLayout) (MainFrame.containerPanel.getLayout());
        cl.show(MainFrame.containerPanel, "addOrdersCard");
    }//GEN-LAST:event_addOrdersNvgActionPerformed

    private void changeOrdersNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeOrdersNvgActionPerformed
        String id = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 0).toString();
        String dateVal = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 2).toString();
        String nameVal = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 3).toString();
        String contactVal = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 4).toString();
        String weightVal = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 5).toString();

        DatePickerSettings dateSettings = new DatePickerSettings();
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        JTextField name = new JTextField();
        JTextField weight = new JTextField();
        JTextField contact = new JTextField();
        DatePicker datePick = new DatePicker(dateSettings);

        name.setText(nameVal);
        datePick.setText(dateVal);
        contact.setText(contactVal);
        weight.setText(weightVal);

        Object[] message = {
            "Nama", name,
            "Kontak", contact,
            "Berat (kg)", weight,
            "Tanggal", datePick
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Ubah Pesanan", JOptionPane.OK_CANCEL_OPTION);

        Order.update(id, name.getText(), datePick.getText(), contact.getText(), weight.getText());
        Order.getAll();
        OrdersPanel.changeOrdersNvg.setEnabled(false);
        OrdersPanel.deleteOrdersNvg.setEnabled(false);
    }//GEN-LAST:event_changeOrdersNvgActionPerformed

    private void deleteOrdersNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteOrdersNvgActionPerformed
        String id = ordersTable.getModel().getValueAt(ordersTable.getSelectedRow(), 0).toString();
        Order.delete(id);
        Order.getAll();
        if (Order.getTotal().equals("0")) {
            OrdersPanel.printOrdersNvg.setEnabled(false);
        }
        totalOrdersLabel.setText(Order.getTotal());
        OrdersPanel.changeOrdersNvg.setEnabled(false);
        OrdersPanel.deleteOrdersNvg.setEnabled(false);
    }//GEN-LAST:event_deleteOrdersNvgActionPerformed

    private void printOrdersNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printOrdersNvgActionPerformed
        Order.print();
    }//GEN-LAST:event_printOrdersNvgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addOrdersNvg;
    public static javax.swing.JButton changeOrdersNvg;
    public static javax.swing.JButton deleteOrdersNvg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable ordersTable;
    public static javax.swing.JButton printOrdersNvg;
    public static javax.swing.JLabel totalOrdersLabel;
    // End of variables declaration//GEN-END:variables
}
