/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import addPanel.AddSalesPanel;
import com.github.lgooddatepicker.components.DatePicker;
import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.Order;
import models.Sales;

/**
 *
 * @author Faruk
 */
public class SalesPanel extends javax.swing.JPanel {

    private final DatePickerSettings dateSettings = new DatePickerSettings();
    private final DatePicker date;

    /**
     * Creates new form SalesPanel
     */
    public SalesPanel() {
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        date = new DatePicker(dateSettings);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        addSalesNvg = new javax.swing.JButton();
        changeSalesNvg = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();

        jLabel31.setText("Info");

        jLabel32.setText("Lainnya");

        addSalesNvg.setText("Tambah");
        addSalesNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesNvgActionPerformed(evt);
            }
        });

        changeSalesNvg.setText("Ubah");
        changeSalesNvg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSalesNvgActionPerformed(evt);
            }
        });

        jLabel30.setText("Penjualan Pupuk");

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(salesTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(changeSalesNvg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSalesNvg))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel30)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSalesNvg)
                    .addComponent(changeSalesNvg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addSalesNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesNvgActionPerformed
        CardLayout cl = (CardLayout) (MainFrame.containerPanel.getLayout());
        cl.show(MainFrame.containerPanel, "addSalesCard");
        AddSalesPanel.orderList.setModel(new DefaultComboBoxModel(Order.getCodes().toArray()));

        Map<String, String> order = Order.getOrderByCode(AddSalesPanel.orderList.getSelectedItem().toString());
        AddSalesPanel.nameLabel.setText(order.get("name"));
        AddSalesPanel.weightLabel.setText(order.get("weight") + " karung");
        AddSalesPanel.dateLabel.setText(order.get("date"));
    }//GEN-LAST:event_addSalesNvgActionPerformed

    private void changeSalesNvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSalesNvgActionPerformed
        String id = salesTable.getModel().getValueAt(salesTable.getSelectedRow(), 0).toString();
        String totalVal = salesTable.getModel().getValueAt(salesTable.getSelectedRow(), 5).toString();
        String dateVal = salesTable.getModel().getValueAt(salesTable.getSelectedRow(), 6).toString();
        JTextField total = new JTextField();

        total.setText(totalVal);
        date.setText(dateVal);
        Object[] message = {
            "Tanggal ", date,
            "Total Bayar", total
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Ubah Penjualan", JOptionPane.OK_CANCEL_OPTION);

        Sales.update(id, date.getText(), total.getText());
        Sales.getAll();
    }//GEN-LAST:event_changeSalesNvgActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalesNvg;
    private javax.swing.JButton changeSalesNvg;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JScrollPane jScrollPane7;
    public static javax.swing.JTable salesTable;
    // End of variables declaration//GEN-END:variables
}
