/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addPanel;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.CardLayout;
import main.MainFrame;
import models.Order;

/**
 *
 * @author Faruk
 */
public class AddOrdersPanel extends javax.swing.JPanel {

    private final DatePickerSettings dateSettings = new DatePickerSettings();

    /**
     * Creates new form AddOrdersPanel
     */
    public AddOrdersPanel() {
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel41 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cancelOrdersButton = new javax.swing.JButton();
        addOrdersButton = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        weightTF = new javax.swing.JTextField();
        datePick = new com.github.lgooddatepicker.components.DatePicker(
            dateSettings);

        jLabel41.setText("Tanggal");

        jLabel37.setText("Tambah Pemesanan Pupuk");

        cancelOrdersButton.setText("Batal");
        cancelOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrdersButtonActionPerformed(evt);
            }
        });

        addOrdersButton.setText("Tambah");
        addOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrdersButtonActionPerformed(evt);
            }
        });

        jLabel38.setText("Nama");

        jLabel39.setText("Kontak");

        jLabel40.setText("Pupuk (karung)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightTF)
                    .addComponent(nameTF)
                    .addComponent(contactTF)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addOrdersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelOrdersButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(datePick, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 292, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addGap(7, 7, 7)
                .addComponent(datePick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addOrdersButton)
                    .addComponent(cancelOrdersButton))
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrdersButtonActionPerformed
        CardLayout cl = (CardLayout) (MainFrame.containerPanel.getLayout());
        cl.show(MainFrame.containerPanel, "ordersCard");
        Order.getAll();
    }//GEN-LAST:event_cancelOrdersButtonActionPerformed

    private void addOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrdersButtonActionPerformed
        String name = nameTF.getText();
        String contact = contactTF.getText();
        String weight = weightTF.getText();
        String date = datePick.getText();

        Order.create(name, date, contact, weight);
        cancelOrdersButtonActionPerformed(evt);
    }//GEN-LAST:event_addOrdersButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrdersButton;
    private javax.swing.JButton cancelOrdersButton;
    private javax.swing.JTextField contactTF;
    private com.github.lgooddatepicker.components.DatePicker datePick;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField weightTF;
    // End of variables declaration//GEN-END:variables
}
