/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addPanel;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import main.MainFrame;
import main.SalesPanel;
import models.Order;
import models.Sales;
import models.Stock;

/**
 *
 * @author Faruk
 */
public class AddSalesPanel extends javax.swing.JPanel {

    private final DatePickerSettings dateSettings = new DatePickerSettings();

    /**
     * Creates new form AddSalesPanel
     */
    public AddSalesPanel() {
        dateSettings.setFormatForDatesCommonEra("yyyy-MM-dd");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderList = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        cancelSalesButton = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        addSalesButton = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker(dateSettings);
        totalPayment = new javax.swing.JFormattedTextField();

        orderList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                orderListItemStateChanged(evt);
            }
        });

        jLabel44.setText("Tanggal Bayar");

        jLabel45.setText("Nama Pemesan");

        jLabel46.setText("Tanggal");

        jLabel47.setText("Berat Pesanan");

        nameLabel.setText("Name");

        dateLabel.setText("21/04/2021");

        weightLabel.setText("50 Karung");

        jLabel42.setText("Tambah Penjualan Pupuk");

        cancelSalesButton.setText("Batal");
        cancelSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelSalesButtonActionPerformed(evt);
            }
        });

        jLabel43.setText("Pesanan");

        addSalesButton.setText("Tambah");
        addSalesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalesButtonActionPerformed(evt);
            }
        });

        jLabel51.setText("Total Bayar");

        totalPayment.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(538, 563, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalPayment)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addSalesButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelSalesButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(orderList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateLabel))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(weightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orderList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLabel)
                    .addComponent(weightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel44)
                .addGap(7, 7, 7)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelSalesButton)
                    .addComponent(addSalesButton))
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSalesButtonActionPerformed
        clearForm();
        CardLayout cl = (CardLayout) (MainFrame.containerPanel.getLayout());
        cl.show(MainFrame.containerPanel, "salesCard");
        Sales.getAll();
        if (Order.getTotal().equals("0")) {
            SalesPanel.addSalesNvg.setEnabled(false);
        }
    }//GEN-LAST:event_cancelSalesButtonActionPerformed

    private void orderListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orderListItemStateChanged
        Map<String, String> order = Order.getOrderByCode(evt.getItem().toString());
        nameLabel.setText(order.get("name"));
        weightLabel.setText(order.get("weight") + " karung");
        dateLabel.setText(order.get("date"));
    }//GEN-LAST:event_orderListItemStateChanged

    private void addSalesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalesButtonActionPerformed
        int totalStock = Integer.valueOf(Stock.getStock());
        Map<String, String> order = Order.getOrderByCode(orderList.getSelectedItem().toString());

        int weight = Integer.valueOf(order.get("weight"));

        if (totalStock < weight) {
            JOptionPane.showMessageDialog(null, "Stok tidak mencukupi, silahkan menambah stok melalui menu produksi", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            String date = datePicker.getText();
            String total = totalPayment.getValue().toString();
            String code = orderList.getSelectedItem().toString();

            Sales.create(code, date, total);

            cancelSalesButtonActionPerformed(evt);
            SalesPanel.totalSalesLabel.setText(Sales.getTotal());
        }
    }//GEN-LAST:event_addSalesButtonActionPerformed

    private void clearForm() {
        datePicker.setText("");
        totalPayment.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalesButton;
    private javax.swing.JButton cancelSalesButton;
    public static javax.swing.JLabel dateLabel;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel51;
    public static javax.swing.JLabel nameLabel;
    public static javax.swing.JComboBox<String> orderList;
    private javax.swing.JFormattedTextField totalPayment;
    public static javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
